import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import Navbar from "@/components/auth/Navbar";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Navbar />
        {children}
      </body>
    </html>
  );
}